version: 2

sources:
  - name: raw
    database: FHV_DB
    schema: RAW
    freshness:
      warn_after: {count: 1, period: month}
      error_after: {count: 3, period: month}
    loaded_at_field: ingestion_timestamp
    tables:
      - name: FHV_TRIPS
        description: "Raw FHV trip data from TLC (2025)"
        columns:
          - name: hvfhs_license_num
            description: "The license number of the high-volume for-hire service."
          - name: request_datetime
            description: "The date and time of the trip request."
          - name: on_scene_datetime
            description: "The date and time the vehicle arrived at the pickup location."
          - name: pickup_datetime
            description: "The date and time the trip started."
            tests:
              - not_null
          - name: dropoff_datetime
            description: "The date and time the trip ended."
          - name: PULocationID
            description: "The pickup location ID."
            tests:
              - not_null
          - name: DOLocationID
            description: "The dropoff location ID."
            tests:
              - not_null
          - name: trip_miles
            description: "The distance of the trip in miles."
          - name: trip_time
            description: "The duration of the trip in seconds."
          - name: base_passenger_fare
            description: "The base fare for the trip."
          - name: tolls
            description: "The amount of tolls paid for the trip."
          - name: bcf
            description: "Black car fund surcharge."
          - name: sales_tax
            description: "Sales tax."
          - name: congestion_surcharge
            description: "Congestion surcharge."
          - name: airport_fee
            description: "Airport fee."
          - name: tips
            description: "Tip amount."
          - name: driver_pay
            description: "Driver pay."
          - name: cbd_congestion_fee
            description: "CBD congestion fee."
          - name: shared_request_flag
            description: "Flag indicating if the trip was a shared request."
          - name: shared_match_flag
            description: "Flag indicating if the trip was a shared match."
          - name: access_a_ride_flag
            description: "Flag indicating if the trip was an Access-A-Ride request."
          - name: wav_request_flag
            description: "Flag indicating if the trip was a wheelchair-accessible vehicle request."
          - name: wav_match_flag
            description: "Flag indicating if the trip was a wheelchair-accessible vehicle match."
