version: 2

sources:
  - name: raw
    database: FHV_DB
    schema: RAW

    config:
      freshness:
        warn_after:
          count: 30
          period: day
        error_after:
          count: 90
          period: day

    tables:
      - name: FHV_TRIPS
        description: Raw FHV trip data from TLC (2025)
        columns:
          - name: pickup_datetime
            tests: [not_null]

          - name: PULocationID
            tests: [not_null]

          - name: DOLocationID
            tests: [not_null]
